# Generated by Django 5.2.6 on 2025-10-08 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('pharmacy_owner', 'Pharmacy Owner'), ('supplier_owner', 'Supplier Owner'), ('staff', 'Staff')], default='customer', max_length=50, verbose_name='Role')),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='en', max_length=10, verbose_name='Default Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100, verbose_name='Governorate')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building_no', models.CharField(max_length=50, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Apartment Number')),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Address Owner')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('user', 'is_default')},
            },
        ),
    ]
