name: 🧠 Feature Implementation (Gherkin)
description: Describe a new feature or API behavior using Gherkin format
title: "[Feature] <feature name>"
labels: ["feature", "backend"]
body:
  - type: markdown
    attributes:
      value: "## 🎯 Feature Summary"
  - type: textarea
    attributes:
      label: "Summary"
      description: "Describe the feature briefly"
      placeholder: "Implement serializers for the Product and Manufacturer models."

  - type: markdown
    attributes:
      value: "## 🧪 Gherkin Scenario"
  - type: textarea
    attributes:
      label: "Scenario"
      description: "Write behavior using Given / When / Then format"
      placeholder: |
        **Scenario:** Serialize Product data
        Given a valid Product instance exists
        When a GET request is sent to /api/catalog/products/
        Then the API should return serialized data including name, price, and manufacturer.

  - type: markdown
    attributes:
      value: "## ✅ Acceptance Criteria"
  - type: textarea
    attributes:
      label: "Checklist"
      placeholder: |
        - [ ] Serializer returns correct fields
        - [ ] Nested Manufacturer is included
        - [ ] All serializer tests pass

  - type: markdown
    attributes:
      value: "## 🔗 Related Info"
  - type: input
    attributes:
      label: "Related Branch"
      placeholder: "03_serializers_api"
  - type: input
    attributes:
      label: "Milestone"
      placeholder: "03 – Serializers & DRF API"
