# Generated by Django 5.2.6 on 2025-10-08 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('supplier', 'Supplier')], max_length=50, verbose_name='Company Type')),
                ('name', models.CharField(max_length=255, verbose_name='Trade Name')),
                ('license_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='License Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Company/Supplier',
                'verbose_name_plural': 'Companies and Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('shipping_available', models.BooleanField(default=True, verbose_name='Shipping Available')),
                ('company', models.ForeignKey(limit_choices_to={'type': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='inventory.company', verbose_name='Parent Company')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('qty_on_hand', models.IntegerField(default=0, verbose_name='Quantity On Hand')),
                ('qty_reserved', models.IntegerField(default=0, verbose_name='Quantity Reserved')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost Price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available for Sale')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='inventory.branch', verbose_name='Branch')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase In'), ('sale', 'Sale Out'), ('adjustment', 'Adjustment')], max_length=50, verbose_name='Movement Type')),
                ('delta_qty', models.IntegerField(verbose_name='Quantity Change (+/-)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Movement Time')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch', verbose_name='Affected Batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Moved By')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.IntegerField(verbose_name='Prediction Horizon (Days)')),
                ('predicted_demand', models.IntegerField(verbose_name='Predicted Demand')),
                ('model_version', models.CharField(max_length=50, verbose_name='Model Version')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Demand Prediction',
                'verbose_name_plural': 'Demand Predictions',
            },
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='inventory_qty_on_hand_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__gte', 0)), name='inventory_qty_reserved_gte_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('branch', 'horizon_days')},
        ),
    ]
