# Generated by Django 5.2.6 on 2025-10-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Active Ingredient')),
            ],
            options={
                'verbose_name': 'Active Ingredient',
                'verbose_name_plural': 'Active Ingredients',
            },
        ),
        migrations.CreateModel(
            name='ATCClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='ATC Code')),
                ('name', models.CharField(max_length=255, verbose_name='ATC Classification')),
            ],
            options={
                'verbose_name': 'ATC Class',
                'verbose_name_plural': 'ATC Classes',
            },
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dosage Form')),
            ],
            options={
                'verbose_name': 'Dosage Form',
                'verbose_name_plural': 'Dosage Forms',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Manufacturer Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('atc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.atcclass', verbose_name='ATC Class')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product (Brand)',
                'verbose_name_plural': 'Products (Brands)',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=50, verbose_name='Strength')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activeingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Ingredient',
                'verbose_name_plural': 'Product Ingredients',
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredients',
            field=models.ManyToManyField(through='catalog.ProductIngredient', to='catalog.activeingredient', verbose_name='Active Ingredients'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_text', models.CharField(help_text='e.g., 500 mg, 10 mg/5ml', max_length=100, verbose_name='Strength Text')),
                ('pack_size', models.IntegerField(verbose_name='Pack Size (Units)')),
                ('barcode_gtin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode/GTIN')),
                ('is_prescription_only', models.BooleanField(default=False, verbose_name='Prescription Only (Rx)')),
                ('is_otc', models.BooleanField(default=False, verbose_name='Over-The-Counter (OTC)')),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.dosageform', verbose_name='Dosage Form')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Parent Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'unique_together': {('product', 'dosage_form', 'pack_size')},
            },
        ),
    ]
